:experimental:
:commandkey: &#8984;
:toc: macro
:source-highlighter: highlight.js

=  Native Java REST API Demo Steps

In this demo, I'll show how to create native images with Micronaut, Quarkus, Spring Boot, and Helidon. You'll see how to run a secure, OAuth 2.0-protected, Java REST API that allows JWT authentication.

**Prerequisites:**

- https://sdkman.io/[SDKMAN] (for Java 21 with GraalVM)
- https://httpie.io/[HTTPie] (a better version of cURL)
- A free https://auth0.com/signup[Auth0 account] and the https://github.com/auth0/auth0-cli#installation[Auth0 CLI]

TIP: The brackets at the end of some steps indicate the IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

toc::[]

== Install a JDK with GraalVM

Use SDKMAN to install Java 21 with GraalVM

  sdk install java 21.0.1-graalce

== Generate an OAuth 2.0 Access Token

. Install the https://github.com/auth0/auth0-cli#installation[
 Auth0 CLI] and run `auth0 login` to connect it to your account.

. Create an access token using Auth0's CLI:
+
[source,shell]
----
auth0 test token -a https://<your-auth0-domain>/api/v2/
----

. Set the access token as a `TOKEN` environment variable in a terminal window.

  TOKEN=eyJraWQiOiJYa2pXdjMzTDRBYU1ZSzNGM...

== Make a Java REST API with Micronaut

. Use SDKMAN to install Micronaut's CLI and create an app:
+
[source,shell]
----
sdk install micronaut
mn create-app com.okta.rest.app -f security-jwt -f micronaut-aot
mv app micronaut
----

. Create `controller/HelloController.java`: [`mn-hello`]
+
[source,java]
----
package com.okta.rest.controller;

import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.annotation.Produces;
import io.micronaut.security.annotation.Secured;
import io.micronaut.security.rules.SecurityRule;

import java.security.Principal;

@Controller("/hello")
public class HelloController {

    @Get
    @Secured(SecurityRule.IS_AUTHENTICATED)
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(Principal principal) {
        return "Hello, " + principal.getName() + "!";
    }

}
----

. Enable and configure JWT security in `src/main/resources/application.properties`: [`mn-security-config`]
+
[source,properties]
----
micronaut.security.token.jwt.signatures.jwks.okta.url=https://dev-06bzs1cu.us.auth0.com/.well-known/jwks.json
----

=== Run and Test Your Micronaut API with HTTPie

. Start your app:

  ./gradlew run

. Use HTTPie to pass the JWT in as a bearer token in the `Authorization` header:

  http :8080/hello Authorization:"Bearer $TOKEN"
+
You should get a 200 response with your user id in it.

=== Build a Native Micronaut App

. Compile your Micronaut app into a native binary:

  ./gradlew nativeCompile

. Start your Micronaut app:

  ./build/native/nativeCompile/app

. Test it with HTTPie and an access token. You may have to generate a new JWT if yours has expired.

  http :8080/hello Authorization:"Bearer $TOKEN"

== Create a Java REST API with Quarkus

. Use SDKMAN to install the Quarkus CLI and create a new app with JWT support:
+
[source,shell]
----
sdk install quarkus
quarkus create app com.okta.rest:quarkus \
  --extension="smallrye-jwt,resteasy-reactive" \
  --gradle
----

. Rename `GreetingResource.java` to `HelloResource.java` and add user information to the `hello()` method: [`qk-hello`]
+
[source,java]
----
package com.okta.rest;

import io.quarkus.security.Authenticated;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.SecurityContext;
import java.security.Principal;

@Path("/hello")
public class HelloResource {

    @GET
    @Authenticated
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(@Context SecurityContext context) {
        Principal userPrincipal = context.getUserPrincipal();
        return "Hello, " + userPrincipal.getName() + "!";
    }
}
----

. Add your Auth0 endpoints to `src/main/resources/application.properties`: [`qk-properties`]
+
[source,properties]
----
mp.jwt.verify.issuer=https://<your-auth0-domain>/
mp.jwt.verify.publickey.location=${mp.jwt.verify.issuer}.well-known/jwks.json
----

. Rename `GreetingResourceTest` to `HelloResourceTest` and modify it to expect a 401 instead of a 200:
+
[source,java]
----
package com.okta.rest;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;

@QuarkusTest
public class HelloResourceTest {

    @Test
    public void testHelloEndpoint() {
        given()
            .when().get("/hello")
            .then()
            .statusCode(401);
    }

}
----

=== Run and Test Your Quarkus API with HTTPie

. Run your Quarkus app:

  quarkus dev
  ./gradlew --console=plain quarkusDev

. Test it from another terminal:

  http :8080/hello

. Test with access token:

  http :8080/hello Authorization:"Bearer $TOKEN"

=== Build a Native Quarkus App

. Compile your Quarkus app into a native binary:

  quarkus build --native
  ./gradlew build -Dquarkus.package.type=native

. Start your Quarkus app:

  ./build/quarkus-1.0.0-SNAPSHOT-runner

. Test it with HTTPie and an access token:

  http :8080/hello Authorization:"Bearer $TOKEN"

== Start a Java REST API with Spring Boot

. Use SDKMAN to install the Spring Boot CLI. Then, create a Spring Boot app with OAuth 2.0 support:
+
[source,shell]
----
sdk install springboot
spring init -d=web,oauth2-resource-server,native \
  --group-id=com.okta.rest --package-name=com.okta.rest spring-boot
----

. Add a `HelloController` class that returns the user's information: [`sb-hello`]
+
[source,java]
----
package com.okta.rest.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.security.Principal;

@RestController
public class HelloController {

    @GetMapping("/hello")
    public String hello(Principal principal) {
        return "Hello, " + principal.getName() + "!";
    }

}
----

. Configure the app to be an OAuth 2.0 resource server by adding the issuer to `application.properties`.
+
[source,properties]
----
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://<your-auth0-domain>/
----

=== Run and Test Your Spring Boot API with HTTPie

. Start your app from your IDE or using a terminal:

  ./gradlew bootRun

. Test your API with an access token.

  http :8080/hello Authorization:"Bearer $TOKEN"

=== Build a Native Spring Boot App

. Compile your Spring Boot app into a native executable:

  ./gradlew nativeCompile
+
TIP: To build a native app and a Docker container, use the Spring Boot Gradle plugin and `./gradlew bootBuildImage`.

. Start your Spring Boot app:

  ./build/native/nativeCompile/spring-boot

. Test your API with an access token.

  http :8080/hello Authorization:"Bearer $TOKEN"

== Build a Java REST API with Helidon

. Use SDKMAN to install the Helidon CLI. Then, create a Helidon app:
+
[source,shell]
----
sdk install helidon
helidon init --flavor MP --groupid com.okta.rest \
  --artifactid helidon --package com.okta.rest --batch
----
+
TIP: See https://blogs.oracle.com/developers/post/migrating-a-helidon-se-application-to-gradle[Migrating a Helidon SE application to Gradle] for Gradle support.

. Add MicroProfile JWT support in `pom.xml`:
+
[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.jwt</groupId>
    <artifactId>helidon-microprofile-jwt-auth</artifactId>
</dependency>
----

. Add a `HelloResource` class that returns the user's information: [`h-hello`]
+
[source,java]
----
package com.okta.rest.controller;

import io.helidon.security.Principal;
import io.helidon.security.annotations.Authenticated;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.core.Context;

@Path("/hello")
public class HelloResource {

    @Authenticated
    @GET
    public String hello(@Context SecurityContext context) {
        return "Hello, " + context.userName() + "!";
    }
}
----

. Add a `HelloApplication` class in `src/main/java/com/okta/rest` to register your resource and configure JWT authentication: [`h-app`]
+
[source,java]
----
package com.okta.rest;

import com.okta.rest.controller.HelloResource;
import org.eclipse.microprofile.auth.LoginConfig;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.core.Application;
import java.util.Set;

@LoginConfig(authMethod = "MP-JWT")
@ApplicationScoped
public class HelloApplication extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return Set.of(HelloResource.class);
    }
}
----

. Add your Auth0 endpoints to `src/main/resources/META-INF/microprofile-config.properties`.
+
[source,properties]
----
mp.jwt.verify.issuer=https://<your-auth0-domain>/
mp.jwt.verify.publickey.location=${mp.jwt.verify.issuer}.well-known/jwks.json
----

=== Run and Test Your Helidon REST API with HTTPie

. Start your app from your IDE or using a terminal:

  helidon dev

. Test your API with an access token.

  http :8080/hello Authorization:"Bearer $TOKEN"

. Delete the default Java classes created by the Helidon CLI:

- On Windows: `del /s *.java`
- On Mac/Linux: `find . -name '*.java' -delete`

=== Build a native Helidon app with GraalVM

. Update `src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties` so native compilation will work with Java 21.
+
[source,properties]
----
Args=--initialize-at-build-time=com.okta.rest \
  --initialize-at-run-time=io.helidon.openapi.ExpandedTypeDescription \
  --report-unsupported-elements-at-runtime \
  -H:+AddAllCharsets
----

. Compile your Helidon app into a native executable using the `native-image` profile:

  mvn package -Pnative-image

. Start your Helidon app:

  ./target/helidon

. Test your API with an access token.

  http :8080/hello Authorization:"Bearer $TOKEN"

== Startup Time Comparison

. Run each image three times before recording the numbers, then each command five times.

. Write each time down, add them up, and divide by five for the average. For example:
+
----
Micronaut: (19 + 18 + 17 + 12 + 19) / 5 = 17
Micronaut (optimized): (18 + 15 + 19 + 20 + 17) / 5 = 17.8
Quarkus: (29 + 26 + 27 + 29 + 25) / 5 = 27.2
Spring Boot: (42 + 43 + 37 + 44 + 36) / 5 = 40.4
Helidon*: (50 + 52 + 42 + 53 + 55) / 5 = 50.4
Helidon (optimized): (33 + 34 + 38 + 37 + 36) / 5 = 35.6
----
+
NOTE: Helidon https://github.com/helidon-io/helidon/issues/7784[requires Java 20].

.Native Java startup times in milliseconds
|===
|Framework | Command executed | Milliseconds to start

|Micronaut | `./micronaut/build/native/nativeCompile/app` | 17
|Micronaut (optimized) | `./micronaut/build/native/nativeOptimizedCompile/app` | 17.8
|Quarkus | `./quarkus/build/quarkus-1.0.0-SNAPSHOT-runner` | 27.2
|Spring Boot | `./spring-boot/build/native/nativeCompile/spring-boot` | 40.4
|Helidon | `./helidon/target/helidon` | 50.4
|Helidon (optimized) | https://github.com/oktadev/auth0-java-rest-api-examples/pull/2[auth0-java-rest-api-examples/pull/2] | 35.6
|===

////
October 19, 2023:
- Micronaut: 17
- Micronaut (optimized): 17.8
- Quarkus: 27.2
- Spring Boot: 40.4
- Helidon: 50.4
- Helidon (optimized): 35.6

October 17, 2023:
- Micronaut: 16.2
- Micronaut (optimized): 16
- Quarkus: 27.8
- Spring Boot: 38.4
- Helidon: 49.2
- Helidon (optimized): 23.8

August 2023:
- Micronaut: 15.6
- Micronaut (optimized): 14
- Quarkus: 36.8
- Spring Boot: 38.2
- Helidon: 48.4
- Helidon (optimized): 30.8

June 2023:
- Micronaut: 33.4
- Micronaut (optimized): 23.8
- Quarkus: 25.8
- Spring Boot: 39.8
- Helidon: 47.6
- Helidon (optimized): 33.2

October 2022:
- Micronaut was 18
- Quarkus was 20.6
- Spring Boot was 39
- Helidon was 43.2
////

== Memory Usage Comparison

Test the memory usage in MB of each app using the command below. Make sure to send an HTTP request to each one before measuring.

[source,shell]
----
ps -o pid,rss,command | grep --color <executable> | awk '{$2=int($2/1024)"M";}{ print;}'
----

Substitute `<executable>` as follows:

.Native Java memory used in megabytes
|===
|Framework | Executable | Megabytes after startup | Megabytes after 1 request| Megabytes after 5 requests

|Micronaut | `app` | 53 | 63 | 64
|Micronaut (optimized) | `app` | 45 | 65 | 67
|Quarkus | `quarkus` | 41 | 51 | 53
|Spring Boot | `spring-boot` | 74 | 84 | 84
|Helidon | `helidon` | 83 | 99 | 117
|Helidon (optimized) | `helidon` | 72 | 89 | 123
|===

IMPORTANT: If you disagree with these numbers and think X framework should be faster, I encourage you to clone https://github.com/oktadev/auth0-java-rest-api-examples[this repo] and run these tests yourself.

----
./build.sh
./start.sh micronaut|quarkus|spring-boot|helidon
./memory.sh $TOKEN micronaut|quarkus|spring-boot|helidon
----

== Native Java REST APIs FTW!

🚀 Find the code on GitHub: https://github.com/oktadev/auth0-java-rest-api-examples[@oktadev/auth0-java-rest-api-examples]
